{"froogle", "google"}
{"froogle", "tmobile"}
{"youtube", "google"}
{"youtube", "tmobile"}
{"yahoo", "time"}
{"yahoo", "myspace"}
{"yahoo", "youtube"}
{"yahoo", "aol"}
{"yahoo", "sbc"}
{"websters", "wikipedia"}
{"berkeley", "stanford"}
{"berkeley", "newsweek"}
{"berkeley", "washington"}
{"wikipedia", "websters"}
{"aol", "websters"}
{"seattle", "washington"}
{"washingtion", "newsweek"}
{"msn", "websters"}
{"msn", "aol"}
